# Generated by Django 5.0.6 on 2024-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id_cabinet', models.AutoField(primary_key=True, serialize=False)),
                ('numder', models.IntegerField()),
                ('special', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id_interval', models.AutoField(primary_key=True, serialize=False)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id_patient', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('snils', models.CharField(max_length=16)),
                ('polis', models.CharField(max_length=16)),
            ],
        ),
    ]
