# Generated by Django 5.0.6 on 2024-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseTables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='interval',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
